name: CD

on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:          
      - name: Check out
        uses: actions/checkout@v2
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.12'
          architecture: x64
      
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            kfp==1.8.2
      - name: run pipeline to kubeflow
        run: python kubeflow_pipeline/pipeline.py --host ${{ secrets.KUBERNETES_HOST }} --namespace ${{ secrets.PIPELINE_NAMESPACE }} --username ${{ secrets.PIPELINE_USER_NAME }} --password ${{ secrets.PIPELINE_USER_PASS }} --manage_url ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: #ml-cicd-msg-test
          SLACK_MESSAGE: 'Upload & Run pipeline :rocket: - ${{job.status}}'
          SLACK_USERNAME: 황종현
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
